FROM debian:bullseye

# Install mariadb

RUN apt-get update && apt-get install -y mariadb-server mariadb-client

# Copy mariadb config

# COPY ./conf/mariadb.cnf /etc/mysql/mariadb.conf.d/50-server.cnf

# Copy mariadb setup script

# COPY ./conf/setup.sh /tmp/setup.sh

# Copy mariadb database

# COPY ./conf/wordpress.sql /tmp/wordpress.sql

# CMD ["bash", "/tmp/setup.sh"]


